### ISSUE TITLE
npg_publish_illumina_run.pl should work with "samplesheet" driver_type

### ISSUE THREAD

**Issue by dkj** [wtsi-npg/npg_irods#45]

**Comment by keithj** [comment]
Currently the LIMS shim [croaks](https://github.com/wtsi-npg/npg_tracking/blob/devel/lib/st/api/lims.pm#L192) when asked to pass on an inappropriate driver initarg.

As the caller constructing the LIMS shim is passing just a string (driver type) can they be expected to know which initargs are appropriate? I don't think so because the use-case includes arbitrary driver types for as-yet-unwritten drivers.

Perhaps it should ignore an inappropriate driver initarg?

**Comment by dkj** [comment]
A calling script could bail if an inappropriate option is given for a given driver type (about which the script knows nothing itself) with the current "tight" construction - so there is a (possibly worth paying) cost to giving it up.

On 12 August 2016 18:23:46 CEST, Keith James <notifications@github.com> wrote:
>Currently the LIMS shim
>[croaks](https://github.com/wtsi-npg/npg_tracking/blob/devel/lib/st/api/lims.pm#L192)
>when asked to pass on an inappropriate driver initarg.
>
>As the caller constructing the LIMS shim is passing just a string
>(driver type) can they be expected to know which initargs are
>appropriate? I don't think so because the use-case includes arbitrary
>driver types for as-yet-unwritten drivers.
>
>Perhaps it should ignore an inappropriate driver initarg?
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/wtsi-npg/npg_irods/issues/45#issuecomment-239492303

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by keithj** [comment]
Resolved by #60
